export { blockchain, IXCoinBlockchain } from "./blockchain.js";
export { IXWallet, pubKeyBytesToAddress, validateAddress } from "./wallet.js";
export { Transaction } from "./transaction.js";
export { Block } from "./block.js";
export { GasSystem } from "./gas.js";
export { MiniVM } from "./vm.js";
export { BlockchainStorage } from "./storage.js";
export { CHAIN_CONFIG } from "./config.js";
export { computeMerkleRoot } from "./merkle.js";
export { GlobalState, emptyGlobalState, withState, computeStateRoot } from "./state.js";
export { applyTransaction, applyBlock, replayStateFromChain } from "./state-machine.js";
